name: Build and deploy ASP.Net Core app to an Azure Web App
env:
  AZURE_WEBAPP_NAME: hyperioportf    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.x'                 # set this to the .NET Core version to use
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '38 14 * * 1'
permissions:
  contents: read
  
jobs:
  AZURE-QA:
    permissions:
      contents: none
    runs-on: windows-latest
    environment:
      name: 'AZURE-QA'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true
        # run test
      - name: Test .NET Core
        run: dotnet test
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
        env:
          ConnectionStrings.BaseDados: ${{ secrets.__CONNECTION_STRING_DATABASE__ }}
          ConnectionStrings.ServiceBus: ${{ secrets.__CONNECTION_STRING_SERVICEBUS__ }}
          ApplicationInsights.InstrumentationKey: ${{ secrets.__APPINSIGHTS_INSTRUMENTATION_KEY__ }}
          ApplicationInsights.ConnectionStringApplicationInsightsKey: ${{ secrets.__CONNECTION_STRING_APPLICATION_INSIGHTS_KEY__ }}
          ApplicationInsights.CloudRoleName: ${{ secrets.__CLOUD_ROLE_NAME__ }}
          Auth.ValidIssuer: ${{ secrets.__HYPER_SECURITY_SSUER_BEARER__ }}
          Auth.ValidAudience: ${{ secrets.__HYPER_SECURITY_AUDIENCE_BEARER__ }}
          Auth.SecurityKey: ${{ secrets.__HYPER_SECURITY_KEY__ }}
          Auth.ExpiresIn: ${{ secrets.__SECURITY_TOKEN_EXPIRES_IN__ }}
          ServiceBus.QueueEmail: ${{ secrets.__QUEUE_EMAIL__ }}
          Mail.ApiKey: ${{ secrets.__SENDGRID_APIKEY_ }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app-qa
          path: ${{env.DOTNET_ROOT}}/myapp
      
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app-qa
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.__AZURE_PORTIFOLIO_API_PUBLISH_PROFILE__ }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
